export type Product = {
  id: number;
  sku?: string;
  name: string;
  category: string;
  price: number;
  oldPrice?: number;
  stock: number;
  onHand?: number;
  reserved?: number;
  minimumStock?: number;
  badge: string;
  emoji: string;
  image?: string;
  active?: boolean;
  storeProductId?: string;
  location?: string;
};

export const categories = [
  { name: "Bebidas", icon: "🥤", slug: "bebidas" },
  { name: "Bomboniere", icon: "🍫", slug: "bomboniere" },
  { name: "Salgadinhos", icon: "🍿", slug: "salgadinhos" },
  { name: "Gelo", icon: "🧊", slug: "gelo" },
  { name: "Higiene", icon: "🧼", slug: "higiene" },
  { name: "Limpeza", icon: "🧽", slug: "limpeza" },
  { name: "Utilidades", icon: "🏠", slug: "utilidades" },
];

// Preços e estoques abaixo são demonstrativos e podem ser alterados em /admin/produtos.
// As imagens são referências públicas de produtos reais. Para operação comercial definitiva,
// prefira fotos próprias ou imagens autorizadas pelo fornecedor/distribuidor.
export const products: Product[] = [
  {
    id: 1,
    name: "Coca-Cola Original 2L",
    category: "Bebidas",
    price: 10.99,
    oldPrice: 12.49,
    stock: 18,
    badge: "Oferta",
    emoji: "🥤",
    image: "https://www.powellsnl.ca/media/uploads/gs1/06700000427_20.png",
    active: true,
  },
  {
    id: 2,
    name: "Guaraná Antarctica 2L",
    category: "Bebidas",
    price: 9.99,
    stock: 16,
    badge: "Mais vendido",
    emoji: "🥤",
    image: "https://m.media-amazon.com/images/I/61aFUMfXk2L._SL1000_.jpg",
    active: true,
  },
  {
    id: 3,
    name: "Fanta Laranja 2L",
    category: "Bebidas",
    price: 9.49,
    stock: 14,
    badge: "",
    emoji: "🥤",
    image: "https://cdn.awsli.com.br/800x800/1847/1847175/produto/94341333/364c5bdfdd.jpg",
    active: true,
  },
  {
    id: 4,
    name: "Água Crystal sem gás 1,5L",
    category: "Bebidas",
    price: 4.49,
    stock: 30,
    badge: "",
    emoji: "💧",
    image: "https://elofarma.com.br/BACKOFFICE/Uploads/Produto/Normal/7894900530032.jpg",
    active: true,
  },
  {
    id: 5,
    name: "Red Bull Energy Drink 250ml",
    category: "Bebidas",
    price: 9.99,
    oldPrice: 11.49,
    stock: 20,
    badge: "Madrugada",
    emoji: "⚡",
    image: "https://down-br.img.susercontent.com/file/de3905e6d774d25363e21ac6a2ff7297",
    active: true,
  },
  {
    id: 6,
    name: "Gelo 5 kg",
    category: "Gelo",
    price: 7.5,
    stock: 12,
    badge: "24h",
    emoji: "🧊",
    active: true,
  },
  {
    id: 7,
    name: "Doritos Queijo Nacho 120g",
    category: "Salgadinhos",
    price: 11.49,
    stock: 15,
    badge: "Mais vendido",
    emoji: "🔺",
    image: "https://carrefourbrfood.vtexassets.com/arquivos/ids/193842562/salgadinho-queijo-nacho-doritos-120g-1.jpg?v=638876002921530000",
    active: true,
  },
  {
    id: 8,
    name: "Ruffles Original 76g",
    category: "Salgadinhos",
    price: 9.49,
    stock: 13,
    badge: "",
    emoji: "🥔",
    image: "https://bretas.vtexassets.com/arquivos/ids/200103/6571ccc5558925a4e889be4e.jpg?v=638375536084870000",
    active: true,
  },
  {
    id: 9,
    name: "Oreo Original 154g",
    category: "Bomboniere",
    price: 6.99,
    stock: 22,
    badge: "",
    emoji: "🍪",
    image: "https://www.tuquetraes.com/imagenes/productos/productos_vipges/A01029037.JPG",
    active: true,
  },
  {
    id: 10,
    name: "Bis ao Leite 100,8g",
    category: "Bomboniere",
    price: 7.99,
    stock: 18,
    badge: "Queridinho",
    emoji: "🍫",
    image: "https://images.tcdn.com.br/img/img_prod/1377318/chocolate_bis_100_8g_ao_leite_169_1_bc46a4e81dee4e6402c7608e4f4802f0.jpg",
    active: true,
  },
  {
    id: 11,
    name: "Sonho de Valsa 20g",
    category: "Bomboniere",
    price: 2.49,
    stock: 35,
    badge: "",
    emoji: "🍬",
    image: "https://images.tcdn.com.br/img/img_prod/1225570/sonho_de_valsa_20g_unidade_1677_2_11a8326e492eefeba861a208a5e1bb40.png",
    active: true,
  },
  {
    id: 12,
    name: "Halls Extra Forte 27,5g",
    category: "Bomboniere",
    price: 2.99,
    stock: 28,
    badge: "",
    emoji: "🍬",
    image: "https://destro.fbitsstatic.net/img/p/bala-halls-preta-extra-forte-27-5g-71233/257769-1.jpg?h=500&qs=ignore&v=202501231555&w=500",
    active: true,
  },
  {
    id: 13,
    name: "Trident Menta 30,6g",
    category: "Bomboniere",
    price: 5.49,
    stock: 25,
    badge: "",
    emoji: "🌿",
    image: "https://ideaspapeleria.com/images/002852/large/4178_0.jpg",
    active: true,
  },
  {
    id: 14,
    name: "Paçoquita Original 18g",
    category: "Bomboniere",
    price: 1.49,
    stock: 40,
    badge: "",
    emoji: "🥜",
    image: "https://images.deliveryhero.io/image/global-menu-service/GV_PT/vendor/880476/product/87f22b4a-fa21-4e8a-a43f-e1568f816443.jpg",
    active: true,
  },
  {
    id: 15,
    name: "Toddy Original 200g",
    category: "Bebidas",
    price: 8.99,
    stock: 10,
    badge: "",
    emoji: "🥛",
    image: "https://images-food.ifcshop.com.br/produto/45684_0_20211118104651.jpg",
    active: true,
  },
  {
    id: 16,
    name: "Colgate Máxima Proteção 90g",
    category: "Higiene",
    price: 6.99,
    stock: 14,
    badge: "Essencial",
    emoji: "🪥",
    image: "https://images.tcdn.com.br/img/img_prod/1017481/creme_dental_maxima_protecao_anticaries_90g_colgate_20613_1_30120a5aa824e4057f956a4181329195.jpg",
    active: true,
  },
  {
    id: 17,
    name: "Sabonete Dove Original 90g",
    category: "Higiene",
    price: 5.99,
    stock: 17,
    badge: "",
    emoji: "🧼",
    image: "https://io.convertiez.com.br/m/farmaponte/shop/products/images/21679/medium/sabonete-dove-original-barra-com-90g_38313.png",
    active: true,
  },
  {
    id: 18,
    name: "Detergente Ypê Neutro 500ml",
    category: "Limpeza",
    price: 3.49,
    stock: 18,
    badge: "Essencial",
    emoji: "🧽",
    image: "https://images.tcdn.com.br/img/img_prod/1234949/detergente_neutro_ype_500ml_1177_1_1bfd127b8d8fe6b7eb77d4aadcee2b5c.jpeg",
    active: true,
  },
  {
    id: 19,
    name: "Papel Higiênico Neve 4 rolos",
    category: "Higiene",
    price: 11.99,
    stock: 11,
    badge: "Última hora",
    emoji: "🧻",
    image: "https://images.tcdn.com.br/img/img_prod/694926/papel_higienico_folha_dupla_pacote_c_4_neve_290008_1_71c81b5ab27764f559adb879a450f5bb.jpg",
    active: true,
  },
  {
    id: 20,
    name: "Pilha Duracell AA 2 unidades",
    category: "Utilidades",
    price: 14.99,
    stock: 9,
    badge: "Última hora",
    emoji: "🔋",
    image: "https://cdn.awsli.com.br/2500x2500/2248/2248510/produto/180107250/pilha-alcalina-duracell-palito-aa-pacote-2u-1-5vmpeuc4gh.jpg",
    active: true,
  },
];

export const adminOrders = [
  { id: "#000157", customer: "Mariana Alves", items: 5, total: 64.8, payment: "PIX • PAGO", time: "21:32", status: "NOVO" },
  { id: "#000156", customer: "Rafael Lima", items: 3, total: 31.47, payment: "DINHEIRO", time: "21:27", status: "NOVO" },
  { id: "#000155", customer: "João Silva", items: 7, total: 82.35, payment: "PIX • PAGO", time: "21:19", status: "SEPARANDO" },
  { id: "#000154", customer: "Ana Paula", items: 2, total: 28.98, payment: "CARTÃO NA ENTREGA", time: "21:11", status: "PRONTO" },
  { id: "#000153", customer: "Carlos Souza", items: 6, total: 71.2, payment: "PIX • PAGO", time: "20:58", status: "EM ENTREGA" },
];

export const lowStock = [
  { product: "Gelo 5 kg", stock: 4, min: 6, location: "Freezer 01" },
  { product: "Ruffles Original 76g", stock: 5, min: 8, location: "Prateleira 03" },
  { product: "Red Bull Energy Drink 250ml", stock: 6, min: 10, location: "Geladeira 01 / B" },
];
