"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { StoreHeader } from "@/components/store-header";
import { useCart } from "@/components/cart-provider";
import { DEFAULT_CITY, DEFAULT_STATE, STORE_WHATSAPP } from "@/lib/config";

const brl = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });
const LAST_ORDER_KEY = "conveniencia24h.lastOrder.v2";
type Payment = "pix" | "cash" | "card";
const paymentLabels: Record<Payment,string> = { pix:"PIX", cash:"Dinheiro", card:"Cartão na entrega" };
const paymentApi: Record<Payment,string> = { pix:"pix", cash:"cash", card:"card_on_delivery" };
type Quote={available:boolean;subtotal:number;fee:number;distanceKm:number|null;driverPayout:number;freeDelivery:boolean;freeDeliveryFrom:number;amountToFreeDelivery:number;source:string;message?:string};

export default function CheckoutPage(){
  const router=useRouter(); const {items,subtotal,clear}=useCart();
  const [payment,setPayment]=useState<Payment>('pix'); const [submitting,setSubmitting]=useState(false); const [clientOrderKey]=useState(()=>crypto.randomUUID()); const [website,setWebsite]=useState('');
  const [form,setForm]=useState({name:'',whatsapp:'',cep:'',street:'',number:'',complement:'',neighborhood:'',city:DEFAULT_CITY,state:DEFAULT_STATE,reference:'',notes:'',changeFor:''});
  const [quote,setQuote]=useState<Quote|null>(null); const [quoting,setQuoting]=useState(false); const [quoteError,setQuoteError]=useState('');
  const missingFields=useMemo(()=>!form.name.trim()||!form.whatsapp.trim()||!form.cep.trim()||!form.street.trim()||!form.number.trim()||!form.neighborhood.trim()||!form.city.trim()||!form.state.trim(),[form]);
  const addressReady=useMemo(()=>form.cep.replace(/\D/g,'').length===8&&form.street.trim().length>1&&!!form.number.trim()&&form.neighborhood.trim().length>1&&form.city.trim().length>1&&form.state.trim().length===2,[form]);
  const delivery=quote?.available?Number(quote.fee):0; const total=subtotal+delivery;
  function updateField(key:keyof typeof form,value:string){setForm(current=>({...current,[key]:value}))}

  useEffect(()=>{if(!addressReady||!items.length){setQuote(null);setQuoteError('');return;}const timer=setTimeout(async()=>{setQuoting(true);setQuoteError('');try{const r=await fetch('/api/shipping/quote',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({items:items.map(item=>({product_id:item.id,quantity:item.qty})),address:{postal_code:form.cep,street:form.street,number:form.number,neighborhood:form.neighborhood,city:form.city,state:form.state}})});const d=await r.json();if(!r.ok)throw new Error(d.error||'quote_failed');setQuote(d.quote);}catch(e){setQuote(null);setQuoteError(e instanceof Error&&e.message==='product_unavailable'?'Um produto não está mais disponível.':'Não foi possível calcular a entrega agora.');}finally{setQuoting(false)}},650);return()=>clearTimeout(timer)},[addressReady,form.cep,form.street,form.number,form.neighborhood,form.city,form.state,items]);

  function buildMessage(orderNumber:string, orderItems:any[], officialSubtotal:number, officialDelivery:number, officialTotal:number, distance:number|null, trackingUrl:string){return [
    `🛒 *NOVO PEDIDO — CONVENIÊNCIA 24H*`,`*Pedido #${orderNumber}*`,``,`👤 *Cliente:* ${form.name}`,`📱 *WhatsApp:* ${form.whatsapp}`,
    `📍 *Entrega:* ${form.street}, ${form.number}${form.complement?` - ${form.complement}`:''} • ${form.neighborhood} • ${form.city}/${form.state} • CEP ${form.cep}`,
    distance!=null?`🛵 *Distância:* ${distance.toFixed(1)} km`:'',form.reference?`🧭 *Referência:* ${form.reference}`:'',form.notes?`📝 *Observações:* ${form.notes}`:'',payment==='cash'&&form.changeFor?`💵 *Troco para:* R$ ${form.changeFor}`:'',
    ``,`📦 *Itens:*`,...orderItems.map((item:any)=>`• ${item.quantity??item.qty}x ${item.product_name??item.name} — ${brl.format(Number(item.total_price??((item.price??item.unit_price)*(item.quantity??item.qty))))}`),
    ``,`Subtotal: ${brl.format(officialSubtotal)}`,`Entrega: ${officialDelivery===0?'GRÁTIS':brl.format(officialDelivery)}`,`*TOTAL: ${brl.format(officialTotal)}*`,``,`💳 *Pagamento:* ${paymentLabels[payment]}`,``,`📦 *Acompanhe seu pedido em tempo real:*`,trackingUrl
  ].filter(Boolean).join('\n')}

  async function finishOrder(){
    if(!items.length||submitting)return;if(missingFields){alert('Preencha todos os campos obrigatórios antes de finalizar.');return;}if(quoting){alert('Aguarde o cálculo da entrega.');return;}if(!quote){alert('Confirme um endereço válido para calcular a entrega.');return;}if(!quote.available){alert(quote.message||'Este endereço está fora da área de entrega.');return;}
    setSubmitting(true); const popup=window.open('about:blank','_blank');
    try{const response=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({client_order_key:clientOrderKey,website,customer:{name:form.name,phone:form.whatsapp},address:{postal_code:form.cep,street:form.street,number:form.number,complement:form.complement,neighborhood:form.neighborhood,city:form.city,state:form.state,reference:form.reference},payment_method:paymentApi[payment],change_for:payment==='cash'?form.changeFor:null,notes:form.notes,items:items.map(item=>({product_id:item.id,quantity:item.qty}))})});
      const d=await response.json().catch(()=>({}));if(!response.ok){if(response.status===422)throw new Error('delivery_unavailable');if(response.status===429)throw new Error('too_many_orders');if(d.error==='insufficient_stock'||d.error==='product_unavailable')throw new Error('stock');throw new Error(d.error||'order_rejected');}
      const order=d.order; const orderNumber=String(order.order_number).padStart(6,'0'); const trackingUrl=`${window.location.origin}/pedido/${order.tracking_token}`; const message=buildMessage(orderNumber,order.items,Number(order.subtotal),Number(order.delivery_fee),Number(order.total),order.delivery_distance_km==null?null:Number(order.delivery_distance_km),trackingUrl); const whatsappUrl=`https://wa.me/${STORE_WHATSAPP}?text=${encodeURIComponent(message)}`;
      localStorage.setItem(LAST_ORDER_KEY,JSON.stringify({trackingToken:order.tracking_token,orderNumber})); clear(); if(popup)popup.location.href=whatsappUrl;else window.location.href=whatsappUrl; router.push(`/pedido/${order.tracking_token}`);
    }catch(e){if(popup)popup.close();const reason=e instanceof Error?e.message:'';if(reason==='stock')alert('Um dos produtos não possui mais estoque suficiente. Atualize a loja e tente novamente.');else if(reason==='delivery_unavailable')alert('O endereço informado está fora da área de entrega configurada.');else if(reason==='too_many_orders')alert('Muitas tentativas em pouco tempo. Aguarde alguns minutos e tente novamente.');else alert('O pedido não pôde ser criado. Tente novamente em instantes.');}finally{setSubmitting(false)}
  }

  if(!items.length)return <div className="min-h-screen bg-[#F8F5EF]"><StoreHeader/><main className="mx-auto max-w-xl px-4 py-14 text-center"><div className="text-6xl">🛒</div><h1 className="mt-5 text-3xl font-black text-[#1F2A44]">Nenhum item para finalizar</h1><Link href="/" className="mt-6 inline-flex rounded-2xl bg-[#1F2A44] px-5 py-3 text-xs font-black text-white">VOLTAR À LOJA</Link></main></div>;

  return <div className="min-h-screen bg-[#F8F5EF]"><StoreHeader/><main className="mx-auto max-w-4xl px-4 py-6 md:px-6 md:py-10"><div><p className="text-xs font-black uppercase tracking-wider text-[#A88A45]">Último passo</p><h1 className="mt-1 text-3xl font-black text-[#1F2A44]">Finalizar pedido</h1><p className="mt-2 text-sm text-slate-500">A entrega é calculada pelo endereço e validada novamente no servidor antes de criar o pedido.</p></div><div className="mt-7 grid gap-5 md:grid-cols-2">
    <section className="rounded-[2rem] border border-[#E8DCC8] bg-white p-5"><div className="mb-5 flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-[#1F2A44] text-sm font-black text-white">1</span><h2 className="font-black">Seus dados</h2></div><div className="space-y-3"><label className="absolute left-[-10000px] top-auto h-px w-px overflow-hidden" aria-hidden="true">Site<input tabIndex={-1} autoComplete="off" value={website} onChange={e=>setWebsite(e.target.value)}/></label><input value={form.name} onChange={e=>updateField('name',e.target.value)} className="h-12 w-full rounded-2xl border border-[#E8DCC8] px-4" placeholder="Nome completo *"/><input value={form.whatsapp} onChange={e=>updateField('whatsapp',e.target.value)} className="h-12 w-full rounded-2xl border border-[#E8DCC8] px-4" placeholder="WhatsApp *" inputMode="tel"/></div></section>
    <section className="rounded-[2rem] border border-[#E8DCC8] bg-white p-5"><div className="mb-5 flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-[#1F2A44] text-sm font-black text-white">2</span><h2 className="font-black">Entrega</h2></div><div className="grid gap-3 sm:grid-cols-2"><input value={form.cep} onChange={e=>updateField('cep',e.target.value)} className="h-12 rounded-2xl border border-[#E8DCC8] px-4 sm:col-span-2" placeholder="CEP *"/><input value={form.street} onChange={e=>updateField('street',e.target.value)} className="h-12 rounded-2xl border border-[#E8DCC8] px-4 sm:col-span-2" placeholder="Rua *"/><input value={form.number} onChange={e=>updateField('number',e.target.value)} className="h-12 rounded-2xl border border-[#E8DCC8] px-4" placeholder="Número *"/><input value={form.complement} onChange={e=>updateField('complement',e.target.value)} className="h-12 rounded-2xl border border-[#E8DCC8] px-4" placeholder="Complemento"/><input value={form.neighborhood} onChange={e=>updateField('neighborhood',e.target.value)} className="h-12 rounded-2xl border border-[#E8DCC8] px-4 sm:col-span-2" placeholder="Bairro *"/><input value={form.city} onChange={e=>updateField('city',e.target.value)} className="h-12 rounded-2xl border border-[#E8DCC8] px-4" placeholder="Cidade *"/><input value={form.state} maxLength={2} onChange={e=>updateField('state',e.target.value.toUpperCase())} className="h-12 rounded-2xl border border-[#E8DCC8] px-4" placeholder="UF *"/><input value={form.reference} onChange={e=>updateField('reference',e.target.value)} className="h-12 rounded-2xl border border-[#E8DCC8] px-4 sm:col-span-2" placeholder="Ponto de referência"/><textarea value={form.notes} onChange={e=>updateField('notes',e.target.value)} className="min-h-24 rounded-2xl border border-[#E8DCC8] p-4 sm:col-span-2" placeholder="Observações"/></div>
      <div className={`mt-4 rounded-2xl p-4 text-sm ${quote?.available?'bg-emerald-50 text-emerald-900':quote&&!quote.available?'bg-rose-50 text-rose-800':'bg-[#F8F5EF] text-slate-600'}`}>{quoting?<span className="font-bold">Calculando distância e entrega...</span>:quote?.available?<div className="flex flex-wrap items-center justify-between gap-2"><div><strong>{quote.freeDelivery?'🎁 Frete grátis':`🛵 Entrega ${brl.format(quote.fee)}`}</strong><p className="mt-1 text-xs">{quote.distanceKm!=null?`${quote.distanceKm.toFixed(1)} km • `:''}{quote.freeDelivery?`Pedido acima de ${brl.format(quote.freeDeliveryFrom)}`:quote.amountToFreeDelivery>0?`Faltam ${brl.format(quote.amountToFreeDelivery)} para frete grátis`:'Entrega calculada'}</p></div></div>:quote&&!quote.available?<strong>{quote.message||'Fora da área de entrega'}</strong>:quoteError?<strong>{quoteError}</strong>:<span>Preencha o endereço para calcular a entrega.</span>}</div>
    </section>
    <section className="rounded-[2rem] border border-[#E8DCC8] bg-white p-5 md:col-span-2"><div className="mb-5 flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-[#1F2A44] text-sm font-black text-white">3</span><h2 className="font-black">Pagamento</h2></div><div className="grid gap-3 sm:grid-cols-3">{([['pix','◈','PIX'],['cash','💵','Dinheiro'],['card','💳','Cartão na entrega']] as const).map(([key,icon,label])=><button key={key} type="button" onClick={()=>setPayment(key)} className={`rounded-2xl border-2 p-4 text-left ${payment===key?'border-[#C6A75E] bg-[#F7F2E9]':'border-[#E8DCC8]'}`}><span className="text-2xl">{icon}</span><p className="mt-2 font-black">{label}</p></button>)}</div>{payment==='cash'&&<input value={form.changeFor} onChange={e=>updateField('changeFor',e.target.value)} className="mt-3 h-12 w-full rounded-2xl border border-[#E8DCC8] px-4" placeholder="Troco para quanto?"/>}</section>
  </div><section className="mt-5 rounded-[2rem] bg-[#1F2A44] p-5 text-white md:flex md:items-center md:justify-between"><div><div className="flex gap-5 text-sm text-[#E8DCC8]"><span>Produtos <strong className="text-white">{brl.format(subtotal)}</strong></span><span>Entrega <strong className="text-white">{quote?.available?(delivery===0?'GRÁTIS':brl.format(delivery)):'a calcular'}</strong></span></div><p className="mt-2 text-3xl font-black">{brl.format(total)}</p></div><button onClick={()=>void finishOrder()} disabled={submitting||quoting||!quote?.available} className="mt-4 h-14 w-full rounded-2xl bg-[#C6A75E] px-6 text-sm font-black text-[#1F2A44] disabled:opacity-40 md:mt-0 md:w-auto">{submitting?'CRIANDO PEDIDO...':`FINALIZAR • ${brl.format(total)}`}</button></section></main></div>
}
