"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { BrandLogo } from "@/components/brand-logo";
import { createClient } from "@/lib/supabase/client";
import { hasPublicSupabaseEnv } from "@/lib/config";

export default function DriverLoginPage(){const router=useRouter();const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [loading,setLoading]=useState(false);const [error,setError]=useState('');async function submit(e:FormEvent){e.preventDefault();setLoading(true);setError('');const supabase=createClient();const result=await supabase.auth.signInWithPassword({email,password});if(result.error){setError('E-mail ou senha inválidos.');setLoading(false);return;}if(result.data.user?.app_metadata?.role!=="driver"){await supabase.auth.signOut();setError('Esta conta não possui perfil de entregador.');setLoading(false);return;}router.replace('/entregador');router.refresh();}return <div className="grid min-h-screen place-items-center bg-[#1F2A44] p-4"><main className="w-full max-w-md rounded-[2rem] bg-white p-6 shadow-2xl sm:p-8"><BrandLogo/><p className="mt-7 text-[10px] font-black uppercase tracking-[.18em] text-[#A88A45]">Equipe de entrega</p><h1 className="mt-1 text-3xl font-black text-[#1F2A44]">Entrar como entregador</h1><p className="mt-2 text-sm text-slate-500">Veja apenas os pedidos atribuídos à sua conta.</p>{error&&<div className="mt-4 rounded-2xl bg-red-50 p-4 text-xs font-bold text-red-700">{error}</div>}<form onSubmit={submit} className="mt-6 space-y-3"><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} className="h-12 w-full rounded-2xl border border-[#E8DCC8] px-4" placeholder="E-mail"/><input required type="password" value={password} onChange={e=>setPassword(e.target.value)} className="h-12 w-full rounded-2xl border border-[#E8DCC8] px-4" placeholder="Senha"/><button disabled={!hasPublicSupabaseEnv()||loading} className="h-12 w-full rounded-2xl bg-[#C6A75E] text-sm font-black text-[#1F2A44] disabled:opacity-40">{loading?'ENTRANDO...':'ENTRAR'}</button></form><Link href="/" className="mt-5 block text-center text-xs font-black text-[#8A7040]">← Voltar para a loja</Link></main></div>}
